import type { Industry } from '@/types';

/**
 * FORTUNE 500 · AI MATURITY DATASET (research compilation, August 2026)
 * =====================================================================
 *
 * A curated snapshot of ~200 of the most prominent U.S. Fortune 500
 * enterprises, each scored 0–100 on AI transformation maturity and annotated
 * with its PUBLIC AI POSITIONING — what the company has actually said or done
 * about AI (earnings-call commentary, product launches, reported deployment
 * numbers, partnerships, governance posture).
 *
 * METHODOLOGY — read before using the scores:
 *   - Scores are DIRECTIONAL ANALYST-STYLE ESTIMATES, not audited metrics.
 *     They are synthesized from public disclosures: earnings-call transcripts,
 *     shareholder letters, product announcements, reported deployment/headcount
 *     figures, and reputable press coverage (e.g. Microsoft: >90% of the
 *     Fortune 500 on M365 Copilot; JPMorgan: ~$2B annual AI spend and 400+
 *     production use cases; Walmart: AI tools for ~1.5M associates).
 *   - The five dimensions mirror the galaxy's maturity model:
 *       1. dataInfrastructure   — cloud/data platform readiness
 *       2. workflowStandardization — process standardization at scale
 *       3. aiDeployment        — live AI use cases in production
 *       4. governance          — responsible-AI policy & ethics posture
 *       5. talent              — AI/ML headcount, research depth, upskilling
 *   - `overall` is a weighted judgment of the five, not a strict average.
 *   - revenue ($M) and employees are approximate recent public figures.
 *   - Fortune 500 membership is drawn from the most recent published list;
 *     a handful of names (e.g. Palantir, Workday) entered only recently.
 *   - Compiled for research purposes only. Not investment advice.
 *
 * Color bands used by the galaxy: low 0–40 · mid 40–70 · high 70–100.
 */

/** Maturity scores, fixed order:
 *  [overall, dataInfrastructure, workflowStandardization, aiDeployment, governance, talent] */
export type MaturityTuple = [number, number, number, number, number, number];

export interface Fortune500AIEntry {
  name: string;
  industry: Industry;
  founded: number;
  /** Approximate annual revenue, USD millions (most recent fiscal year). */
  revenue: number;
  /** Approximate headcount (most recent public figure). */
  employees: number;
  location: string; // HQ
  m: MaturityTuple;
  /** Marks the AI flagship companies (pulse in the galaxy). */
  featured?: boolean;
  /** Public AI positioning — what the company has said/done, with anchors. */
  note: string;
}

export const FORTUNE500_AI_COMPANIES: Fortune500AIEntry[] = [
  // ───────────────────────────────────────────── TECHNOLOGY ─────────────────────────────────────────────
  {
    name: 'Nvidia',
    industry: 'Technology',
    founded: 1993,
    revenue: 235000,
    employees: 36000,
    location: 'Santa Clara, CA',
    m: [97, 95, 82, 98, 86, 97],
    featured: true,
    note: 'The AI infrastructure company — data-center compute is ~92% of revenue, ~$500B of AI-chip orders across 2025–26, and Huang publicly frames AI as a $3–4T market and the "new industrial revolution".',
  },
  {
    name: 'Microsoft',
    industry: 'Technology',
    founded: 1975,
    revenue: 281700,
    employees: 228000,
    location: 'Redmond, WA',
    m: [95, 96, 85, 95, 90, 96],
    featured: true,
    note: 'Nadella reports >90% of the Fortune 500 use Microsoft 365 Copilot, an AI business past a $37B annual revenue run rate, and Copilot at 30M+ paid seats with autonomous agents the stated next phase.',
  },
  {
    name: 'Alphabet',
    industry: 'Technology',
    founded: 1998,
    revenue: 410000,
    employees: 183000,
    location: 'Mountain View, CA',
    m: [93, 94, 78, 94, 82, 95],
    featured: true,
    note: 'Gemini models woven through Search, Cloud and Workspace, TPUs and DeepMind anchor an AI-first strategy, and Pichai publicly calls AI "the platform shift of a lifetime" with Cloud AI growth cited on every earnings call.',
  },
  {
    name: 'Amazon',
    industry: 'Technology',
    founded: 1994,
    revenue: 700000,
    employees: 1550000,
    location: 'Seattle, WA',
    m: [90, 95, 84, 91, 84, 92],
    featured: true,
    note: 'AWS AI revenue run rate crossed $15B (Jassy, Q1 2026), custom Trainium/Inferentia chip business roughly doubled to ~$20B, and Jassy publicly projects AI could make AWS a $600B business by 2036.',
  },
  {
    name: 'Meta',
    industry: 'Technology',
    founded: 2004,
    revenue: 215000,
    employees: 74000,
    location: 'Menlo Park, CA',
    m: [86, 88, 76, 89, 74, 90],
    featured: true,
    note: 'Open-sourced Llama, formed Superintelligence Labs for AGI research, and Zuckerberg publicly frames AI as the primary driver of ad targeting and recommendation revenue — "the most important trend of our time".',
  },
  {
    name: 'Oracle',
    industry: 'Technology',
    founded: 1977,
    revenue: 64000,
    employees: 159000,
    location: 'Austin, TX',
    m: [84, 86, 74, 87, 78, 82],
    featured: true,
    note: 'Aggressive AI-infrastructure push — Stargate data-center deals, OCI AI superclusters, and Ellison publicly describing an "AI arms race" with AI cloud backlog the headline metric on earnings calls.',
  },
  {
    name: 'Broadcom',
    industry: 'Technology',
    founded: 1961,
    revenue: 51000,
    employees: 37000,
    location: 'Palo Alto, CA',
    m: [85, 84, 72, 88, 80, 84],
    note: 'Custom AI accelerators for hyperscalers (Google TPUs, OpenAI) plus VMware AI; Hock Tan publicly calls AI networking and compute the company\'s largest growth engine.',
  },
  {
    name: 'Palantir',
    industry: 'Technology',
    founded: 2003,
    revenue: 2900,
    employees: 4500,
    location: 'Denver, CO',
    m: [86, 88, 80, 88, 72, 86],
    featured: true,
    note: 'AIP became its flagship product with triple-digit growth; CEO Alex Karp publicly frames enterprise AI adoption as an existential/national priority and the company entered the Fortune 500 in 2025.',
  },
  {
    name: 'ServiceNow',
    industry: 'Technology',
    founded: 2004,
    revenue: 10500,
    employees: 25000,
    location: 'Santa Clara, CA',
    m: [85, 84, 82, 86, 80, 82],
    note: 'Positioned as the enterprise "AI platform for business transformation"; McDermott publicly touts AI agents on the Now Platform as the fastest-growing product line.',
  },
  {
    name: 'Salesforce',
    industry: 'Technology',
    founded: 1999,
    revenue: 37900,
    employees: 72000,
    location: 'San Francisco, CA',
    m: [82, 83, 80, 84, 78, 80],
    note: 'Agentforce agentic AI is the centerpiece of earnings calls; Benioff publicly claims tens of thousands of Agentforce deployments and positions Salesforce as the "AI CRM".',
  },
  {
    name: 'Accenture',
    industry: 'Technology',
    founded: 1989,
    revenue: 65000,
    employees: 774000,
    location: 'New York, NY',
    m: [80, 84, 78, 82, 80, 82],
    note: 'Invested $3B+ in AI and publicly reports thousands of generative-AI client projects, positioning "reinvention" consulting around AI as its growth engine.',
  },
  {
    name: 'Adobe',
    industry: 'Technology',
    founded: 1982,
    revenue: 21400,
    employees: 30000,
    location: 'San Jose, CA',
    m: [79, 82, 74, 82, 78, 80],
    note: 'Firefly generative models embedded across Creative Cloud with public messaging around IP-safe, commercially licensed AI and "AI-assisted creativity".',
  },
  {
    name: 'AMD',
    industry: 'Technology',
    founded: 1969,
    revenue: 25800,
    employees: 26000,
    location: 'Santa Clara, CA',
    m: [83, 82, 72, 86, 78, 84],
    note: 'MI300/MI350 accelerators positioned head-to-head against Nvidia; Lisa Su publicly targets the AI data-center TAM as AMD\'s largest growth opportunity.',
  },
  {
    name: 'Cisco',
    industry: 'Technology',
    founded: 1984,
    revenue: 54000,
    employees: 90500,
    location: 'San Jose, CA',
    m: [68, 76, 68, 66, 74, 72],
    note: 'Splunk acquisition plus "AI-ready network" messaging; Robbins publicly frames AI workloads as driving a networking supercycle.',
  },
  {
    name: 'IBM',
    industry: 'Technology',
    founded: 1911,
    revenue: 62000,
    employees: 282000,
    location: 'Armonk, NY',
    m: [78, 82, 76, 78, 84, 80],
    note: 'watsonx platform and open-source Granite models with an "AI for business" stance; publicly reports thousands of watsonx engagements and enterprise AI pilots.',
  },
  {
    name: 'Dell Technologies',
    industry: 'Technology',
    founded: 1984,
    revenue: 88000,
    employees: 120000,
    location: 'Round Rock, TX',
    m: [66, 72, 64, 68, 70, 66],
    note: 'Publicly cites a multi-billion-dollar AI-server backlog and positions AI-optimized servers and "AI factory" services as its growth story.',
  },
  {
    name: 'Hewlett Packard Enterprise',
    industry: 'Technology',
    founded: 2015,
    revenue: 30000,
    employees: 60000,
    location: 'Spring, TX',
    m: [72, 76, 66, 74, 72, 72],
    note: 'AI systems (Cray) orders and the Juniper networking deal anchor Neri\'s public "AI-native portfolio" narrative.',
  },
  {
    name: 'Intel',
    industry: 'Technology',
    founded: 1968,
    revenue: 53000,
    employees: 125000,
    location: 'Santa Clara, CA',
    m: [58, 62, 56, 58, 66, 60],
    note: 'Public AI positioning centers on the foundry push (Intel 18A) and AI PCs (Core Ultra) rather than data-center GPUs; Gaudi lags in the accelerator race.',
  },
  {
    name: 'Qualcomm',
    industry: 'Technology',
    founded: 1985,
    revenue: 39000,
    employees: 49000,
    location: 'San Diego, CA',
    m: [70, 74, 64, 72, 72, 74],
    note: 'On-device AI positioning (AI PCs, phones, automotive); publicly touts NPU leadership and hybrid device+cloud inference as its differentiation.',
  },
  {
    name: 'Micron',
    industry: 'Technology',
    founded: 1978,
    revenue: 25000,
    employees: 48000,
    location: 'Boise, ID',
    m: [69, 72, 62, 72, 70, 68],
    note: 'HBM for AI accelerators sold out; Mehrotra publicly frames AI memory demand as a multi-year supercycle driving record revenue.',
  },
  {
    name: 'Apple',
    industry: 'Technology',
    founded: 1976,
    revenue: 411000,
    employees: 164000,
    location: 'Cupertino, CA',
    m: [72, 78, 62, 74, 84, 76],
    note: 'Apple Intelligence across devices with a privacy-first, on-device public stance; slower to monetize generative AI but deeply embedded in hardware and OS.',
  },
  {
    name: 'Intuit',
    industry: 'Technology',
    founded: 1983,
    revenue: 16000,
    employees: 18000,
    location: 'Mountain View, CA',
    m: [74, 78, 72, 76, 76, 74],
    note: 'GenOS and the Intuit Assist assistant; public messaging frames AI as the core of QuickBooks and TurboTax personalization and automation.',
  },
  {
    name: 'Workday',
    industry: 'Technology',
    founded: 2005,
    revenue: 8400,
    employees: 19000,
    location: 'Pleasanton, CA',
    m: [70, 74, 72, 72, 74, 72],
    note: 'Illuminate AI and agentic HR/finance AI; publicly positioned as "AI for HR and finance" with a governance-first pitch.',
  },
  {
    name: 'Palo Alto Networks',
    industry: 'Technology',
    founded: 2005,
    revenue: 8800,
    employees: 15000,
    location: 'Santa Clara, CA',
    m: [75, 76, 72, 76, 74, 76],
    note: 'Precision AI security platform; Arora publicly frames AI-first security as the industry\'s growth engine and ties platform consolidation to AI agents.',
  },
  {
    name: 'Cognizant',
    industry: 'Technology',
    founded: 1994,
    revenue: 19400,
    employees: 340000,
    location: 'Teaneck, NJ',
    m: [72, 74, 72, 72, 74, 74],
    note: 'Publicly commits to large-scale gen-AI upskilling and "AI-fueled services", positioning AI as reshaping the IT-services delivery model.',
  },
  {
    name: 'Applied Materials',
    industry: 'Technology',
    founded: 1967,
    revenue: 27000,
    employees: 34000,
    location: 'Santa Clara, CA',
    m: [66, 68, 60, 68, 70, 68],
    note: 'Semiconductor equipment supplier riding AI-chip demand; public commentary ties growth to AI infrastructure buildout.',
  },
  {
    name: 'HP Inc',
    industry: 'Technology',
    founded: 2015,
    revenue: 53000,
    employees: 58000,
    location: 'Palo Alto, CA',
    m: [54, 58, 52, 54, 60, 52],
    note: '"AI every day" AI-PC push and HP Print AI; modest public AI positioning relative to peers.',
  },
  {
    name: 'Western Digital',
    industry: 'Technology',
    founded: 1970,
    revenue: 13000,
    employees: 51000,
    location: 'San Jose, CA',
    m: [50, 54, 50, 52, 56, 50],
    note: 'AI-driven storage demand (data-center HDDs) cited on earnings; limited end-user AI strategy.',
  },
  {
    name: 'Texas Instruments',
    industry: 'Technology',
    founded: 1930,
    revenue: 16000,
    employees: 34000,
    location: 'Dallas, TX',
    m: [48, 52, 46, 48, 54, 48],
    note: 'Public AI commentary focuses on edge/embedded AI demand for analog chips; conservative, low-profile posture.',
  },
  {
    name: 'Motorola Solutions',
    industry: 'Technology',
    founded: 1928,
    revenue: 10000,
    employees: 21000,
    location: 'Chicago, IL',
    m: [66, 70, 64, 66, 70, 66],
    note: 'Public-safety AI (video analytics, command-center AI); Brown publicly positions AI as core to mission-critical communications.',
  },

  // ───────────────────────────────────────── FINANCIAL SERVICES ─────────────────────────────────────────
  {
    name: 'JPMorgan Chase',
    industry: 'Financial Services',
    founded: 1799,
    revenue: 190000,
    employees: 317000,
    location: 'New York, NY',
    m: [93, 94, 88, 93, 90, 94],
    featured: true,
    note: '~$2B annual AI spend within a $17–19.8B tech budget, 2,000+ AI/ML specialists, 400+ AI use cases in production and roughly half of employees using gen-AI daily; Dimon\'s letters call AI "transformative for every job".',
  },
  {
    name: 'Goldman Sachs',
    industry: 'Financial Services',
    founded: 1869,
    revenue: 54000,
    employees: 46600,
    location: 'New York, NY',
    m: [80, 82, 76, 82, 78, 82],
    note: 'GS AI assistant with 10,000+ developers on AI coding tools; publicly frames gen-AI as a productivity unlock across investment banking and trading.',
  },
  {
    name: 'Morgan Stanley',
    industry: 'Financial Services',
    founded: 1935,
    revenue: 62000,
    employees: 90000,
    location: 'New York, NY',
    m: [82, 84, 78, 84, 80, 82],
    note: 'First-mover OpenAI partnership (2023) powering AI @Morgan Stanley for advisors; publicly reports strong advisor adoption and an agent roadmap.',
  },
  {
    name: 'Bank of America',
    industry: 'Financial Services',
    founded: 1998,
    revenue: 102000,
    employees: 213000,
    location: 'Charlotte, NC',
    m: [78, 80, 76, 80, 80, 78],
    note: 'Erica virtual assistant with 25M+ users and billions of interactions; publicly touts AI in fraud detection and customer service at scale.',
  },
  {
    name: 'Citigroup',
    industry: 'Financial Services',
    founded: 1812,
    revenue: 80000,
    employees: 229000,
    location: 'New York, NY',
    m: [72, 74, 72, 72, 74, 72],
    note: '"AI factory" pilot model and gen-AI rollout to employees; public comments emphasize responsible-AI governance alongside deployment.',
  },
  {
    name: 'Wells Fargo',
    industry: 'Financial Services',
    founded: 1852,
    revenue: 83000,
    employees: 218000,
    location: 'San Francisco, CA',
    m: [68, 70, 66, 66, 72, 68],
    note: 'Fargo copilot and AI fraud tools; publicly cautious, putting risk governance ahead of deployment speed.',
  },
  {
    name: 'American Express',
    industry: 'Financial Services',
    founded: 1850,
    revenue: 66000,
    employees: 77000,
    location: 'New York, NY',
    m: [80, 82, 78, 80, 80, 80],
    note: 'ML-driven fraud and rewards; publicly reports gen-AI improving customer service and personalization at scale.',
  },
  {
    name: 'Capital One',
    industry: 'Financial Services',
    founded: 1988,
    revenue: 42000,
    employees: 55000,
    location: 'McLean, VA',
    m: [78, 82, 74, 78, 78, 80],
    note: 'Self-described "tech company that happens to be a bank"; Eno assistant, ML-first cloud migration, and a public AI-engineering culture.',
  },
  {
    name: 'Visa',
    industry: 'Financial Services',
    founded: 1958,
    revenue: 36000,
    employees: 31000,
    location: 'San Francisco, CA',
    m: [85, 86, 80, 86, 82, 84],
    note: 'AI fraud and risk across VisaNet with generative-AI/agent tools for issuers and merchants; McInerney publicly frames AI as core to payments.',
  },
  {
    name: 'Mastercard',
    industry: 'Financial Services',
    founded: 1966,
    revenue: 28000,
    employees: 34000,
    location: 'Purchase, NY',
    m: [84, 86, 80, 84, 82, 82],
    note: 'Decision Intelligence and generative-AI "AI-powered decisioning"; publicly reports AI models blocking billions of dollars in fraud.',
  },
  {
    name: 'PayPal',
    industry: 'Financial Services',
    founded: 1998,
    revenue: 32000,
    employees: 27000,
    location: 'San Jose, CA',
    m: [72, 76, 70, 72, 72, 72],
    note: 'AI-driven risk and personalization; public statements push an "AI-first" product strategy under CEO Chriss.',
  },
  {
    name: 'BlackRock',
    industry: 'Financial Services',
    founded: 1988,
    revenue: 20000,
    employees: 20000,
    location: 'New York, NY',
    m: [70, 72, 68, 70, 74, 70],
    note: 'Aladdin platform AI; Fink\'s public letters emphasize AI\'s productivity and data advantages for asset management.',
  },
  {
    name: 'Charles Schwab',
    industry: 'Financial Services',
    founded: 1971,
    revenue: 19000,
    employees: 35000,
    location: 'Westlake, TX',
    m: [60, 64, 58, 60, 62, 60],
    note: 'AI service/support tools for advisers; public commentary focused on productivity tools rather than frontier AI.',
  },
  {
    name: 'BNY Mellon',
    industry: 'Financial Services',
    founded: 1784,
    revenue: 18000,
    employees: 51000,
    location: 'New York, NY',
    m: [64, 68, 62, 64, 68, 64],
    note: 'AI in custody and operations; publicly highlights gen-AI pilots and data modernization.',
  },
  {
    name: 'State Street',
    industry: 'Financial Services',
    founded: 1792,
    revenue: 13000,
    employees: 42000,
    location: 'Boston, MA',
    m: [58, 62, 58, 58, 62, 58],
    note: 'Moderate AI automation in the back office; public commentary on gen-AI experimentation.',
  },
  {
    name: 'US Bancorp',
    industry: 'Financial Services',
    founded: 1863,
    revenue: 27000,
    employees: 77000,
    location: 'Minneapolis, MN',
    m: [56, 60, 56, 56, 60, 56],
    note: 'Smart assistant and AI in risk; measured public posture.',
  },
  {
    name: 'PNC Financial',
    industry: 'Financial Services',
    founded: 1852,
    revenue: 21000,
    employees: 60000,
    location: 'Pittsburgh, PA',
    m: [56, 60, 56, 56, 60, 56],
    note: 'AI in fraud and collections; limited public generative-AI narrative.',
  },
  {
    name: 'Truist',
    industry: 'Financial Services',
    founded: 1872,
    revenue: 22000,
    employees: 51000,
    location: 'Charlotte, NC',
    m: [54, 58, 54, 54, 58, 54],
    note: 'Early gen-AI pilots (employee copilot); cautious public stance.',
  },
  {
    name: 'Intercontinental Exchange',
    industry: 'Financial Services',
    founded: 2000,
    revenue: 12000,
    employees: 13000,
    location: 'Atlanta, GA',
    m: [68, 70, 66, 68, 68, 66],
    note: 'AI in data/analytics (ICE Data Services); public comments on AI-powered trading and data tools.',
  },
  {
    name: 'S&P Global',
    industry: 'Financial Services',
    founded: 1917,
    revenue: 13000,
    employees: 40000,
    location: 'New York, NY',
    m: [72, 74, 70, 72, 74, 72],
    note: 'Kensho AI acquisition and AI in ratings/data; publicly positioned as an AI-native data provider.',
  },
  {
    name: 'Fiserv',
    industry: 'Financial Services',
    founded: 1984,
    revenue: 20000,
    employees: 44000,
    location: 'Brookfield, WI',
    m: [70, 72, 70, 70, 72, 70],
    note: 'Clover and banking AI; publicly touts AI-powered risk/underwriting and gen-AI assistant tools for financial institutions.',
  },
  {
    name: 'FIS',
    industry: 'Financial Services',
    founded: 1968,
    revenue: 10000,
    employees: 64000,
    location: 'Jacksonville, FL',
    m: [66, 68, 66, 66, 70, 66],
    note: 'AI in banking/wealth platforms; moderate public AI commentary amid transformation.',
  },

  // ─────────────────────────────────────────────── INSURANCE ───────────────────────────────────────────────
  {
    name: 'Berkshire Hathaway',
    industry: 'Insurance',
    founded: 1839,
    revenue: 364000,
    employees: 397000,
    location: 'Omaha, NE',
    m: [50, 54, 48, 50, 56, 50],
    note: 'Conglomerate with limited public AI commentary (Buffett\'s skeptical framing) though GEICO deploys ML in claims and underwriting.',
  },
  {
    name: 'Progressive',
    industry: 'Insurance',
    founded: 1937,
    revenue: 62000,
    employees: 62000,
    location: 'Mayfield Village, OH',
    m: [72, 74, 72, 72, 74, 70],
    note: 'Usage-based insurance and AI claims; publicly touts ML pricing and telematics (Snapshot) as competitive advantages.',
  },
  {
    name: 'Allstate',
    industry: 'Insurance',
    founded: 1931,
    revenue: 61000,
    employees: 54000,
    location: 'Northbrook, IL',
    m: [66, 68, 64, 66, 70, 64],
    note: 'AI photo-claims and Arity telematics; public comments on gen-AI in claims processing.',
  },
  {
    name: 'Chubb',
    industry: 'Insurance',
    founded: 1985,
    revenue: 57000,
    employees: 40000,
    location: 'New York, NY',
    m: [68, 70, 66, 68, 72, 66],
    note: 'AI in underwriting and claims; public statements frame AI as a risk-pricing advantage.',
  },
  {
    name: 'Travelers',
    industry: 'Insurance',
    founded: 1853,
    revenue: 43000,
    employees: 33000,
    location: 'New York, NY',
    m: [64, 66, 62, 64, 68, 62],
    note: 'AI in claims and underwriting; moderate public gen-AI pilot commentary.',
  },
  {
    name: 'MetLife',
    industry: 'Insurance',
    founded: 1868,
    revenue: 67000,
    employees: 45000,
    location: 'New York, NY',
    m: [64, 66, 62, 64, 66, 62],
    note: 'AI customer-service agent-assist; public "AI-first" digital strategy comments.',
  },
  {
    name: 'Prudential Financial',
    industry: 'Insurance',
    founded: 1875,
    revenue: 56000,
    employees: 39000,
    location: 'Newark, NJ',
    m: [62, 64, 60, 62, 66, 60],
    note: 'AI in advice and operations; measured public positioning.',
  },
  {
    name: 'AIG',
    industry: 'Insurance',
    founded: 1919,
    revenue: 50000,
    employees: 24000,
    location: 'New York, NY',
    m: [60, 62, 60, 60, 64, 58],
    note: 'AI in underwriting and claims; public comments on data modernization.',
  },
  {
    name: 'Liberty Mutual',
    industry: 'Insurance',
    founded: 1912,
    revenue: 50000,
    employees: 45000,
    location: 'Boston, MA',
    m: [62, 64, 60, 62, 64, 60],
    note: 'Computer-vision AI claims and gen-AI experimentation publicly discussed.',
  },
  {
    name: 'The Hartford',
    industry: 'Insurance',
    founded: 1810,
    revenue: 26000,
    employees: 19000,
    location: 'Hartford, CT',
    m: [60, 62, 58, 60, 62, 58],
    note: 'AI in underwriting and claims; moderate public AI narrative.',
  },

  // ─────────────────────────────────────────────── HEALTHCARE ───────────────────────────────────────────────
  {
    name: 'UnitedHealth Group',
    industry: 'Healthcare',
    founded: 1977,
    revenue: 447600,
    employees: 440000,
    location: 'Minnetonka, MN',
    m: [85, 88, 80, 86, 84, 84],
    featured: true,
    note: '~$1.5B AI investment planned for 2026 including the Avery generative-AI platform for clinical/admin work; publicly frames AI as the largest lever on healthcare cost and quality.',
  },
  {
    name: 'Eli Lilly',
    industry: 'Healthcare',
    founded: 1876,
    revenue: 45000,
    employees: 43000,
    location: 'Indianapolis, IN',
    m: [78, 80, 74, 78, 76, 80],
    note: 'AI in drug discovery and clinical trials (multiple collaborations); public statements on AI accelerating R&D.',
  },
  {
    name: 'Pfizer',
    industry: 'Healthcare',
    founded: 1849,
    revenue: 64000,
    employees: 88000,
    location: 'New York, NY',
    m: [74, 76, 72, 74, 76, 76],
    note: 'AI across R&D and commercial; public "AI-first" transformation comments from leadership.',
  },
  {
    name: 'Johnson & Johnson',
    industry: 'Healthcare',
    founded: 1886,
    revenue: 89000,
    employees: 132000,
    location: 'New Brunswick, NJ',
    m: [76, 78, 72, 76, 78, 76],
    note: 'MedTech AI (surgical robotics, imaging) and AI in R&D; public statements on AI-enabled surgery.',
  },
  {
    name: 'Merck',
    industry: 'Healthcare',
    founded: 1891,
    revenue: 64000,
    employees: 71000,
    location: 'Rahway, NJ',
    m: [70, 72, 68, 70, 74, 72],
    note: 'AI in R&D and manufacturing; public gen-AI pilot commentary.',
  },
  {
    name: 'Abbott Laboratories',
    industry: 'Healthcare',
    founded: 1888,
    revenue: 42000,
    employees: 114000,
    location: 'Abbott Park, IL',
    m: [68, 70, 66, 68, 72, 68],
    note: 'AI in diagnostics and connected devices; measured public positioning.',
  },
  {
    name: 'Amgen',
    industry: 'Healthcare',
    founded: 1980,
    revenue: 34000,
    employees: 26000,
    location: 'Thousand Oaks, CA',
    m: [66, 68, 64, 66, 70, 68],
    note: 'AI in drug discovery via collaborations; public comments on computational biology.',
  },
  {
    name: 'Medtronic',
    industry: 'Healthcare',
    founded: 1949,
    revenue: 33000,
    employees: 95000,
    location: 'Dublin, IE',
    m: [70, 72, 68, 70, 72, 70],
    note: 'AI-embedded devices (GI Genius, diabetes algorithms); public AI device-pipeline commentary.',
  },
  {
    name: 'Boston Scientific',
    industry: 'Healthcare',
    founded: 1979,
    revenue: 16700,
    employees: 45000,
    location: 'Marlborough, MA',
    m: [64, 66, 62, 64, 66, 62],
    note: 'AI-embedded devices; modest public AI narrative.',
  },
  {
    name: 'Stryker',
    industry: 'Healthcare',
    founded: 1941,
    revenue: 22900,
    employees: 52000,
    location: 'Kalamazoo, MI',
    m: [62, 64, 60, 62, 64, 60],
    note: 'AI-assisted surgery (Mako robotics); public comments on AI-enabled medtech.',
  },
  {
    name: 'CVS Health',
    industry: 'Healthcare',
    founded: 1963,
    revenue: 357000,
    employees: 300000,
    location: 'Woonsocket, RI',
    m: [62, 66, 62, 62, 64, 60],
    note: 'AI in pharmacy and claims; public gen-AI efficiency commentary.',
  },
  {
    name: 'Cigna Group',
    industry: 'Healthcare',
    founded: 1982,
    revenue: 245000,
    employees: 70000,
    location: 'Bloomfield, CT',
    m: [66, 68, 64, 66, 68, 64],
    note: 'AI in care management and claims; moderate public AI narrative.',
  },
  {
    name: 'Humana',
    industry: 'Healthcare',
    founded: 1961,
    revenue: 120000,
    employees: 67000,
    location: 'Louisville, KY',
    m: [60, 62, 60, 60, 62, 58],
    note: 'AI in member services; cautious public posture.',
  },
  {
    name: 'Elevance Health',
    industry: 'Healthcare',
    founded: 1946,
    revenue: 172000,
    employees: 98000,
    location: 'Indianapolis, IN',
    m: [60, 62, 58, 60, 62, 58],
    note: 'AI in claims and member experience; public gen-AI pilots.',
  },
  {
    name: 'Centene',
    industry: 'Healthcare',
    founded: 1984,
    revenue: 156000,
    employees: 74000,
    location: 'St. Louis, MO',
    m: [54, 58, 54, 54, 58, 52],
    note: 'Limited public AI strategy; cost-focused posture.',
  },
  {
    name: 'HCA Healthcare',
    industry: 'Healthcare',
    founded: 1968,
    revenue: 70000,
    employees: 284000,
    location: 'Nashville, TN',
    m: [58, 60, 58, 58, 60, 56],
    note: 'AI in clinical operations and documentation; public efficiency commentary.',
  },
  {
    name: 'McKesson',
    industry: 'Healthcare',
    founded: 1833,
    revenue: 322000,
    employees: 51000,
    location: 'Irving, TX',
    m: [64, 68, 62, 64, 66, 62],
    note: 'AI in pharmaceutical supply chain; moderate public AI narrative.',
  },
  {
    name: 'Cardinal Health',
    industry: 'Healthcare',
    founded: 1971,
    revenue: 236000,
    employees: 48000,
    location: 'Dublin, OH',
    m: [58, 62, 58, 58, 60, 56],
    note: 'AI in distribution; limited public commentary.',
  },
  {
    name: 'Cencora',
    industry: 'Healthcare',
    founded: 2018,
    revenue: 293000,
    employees: 46000,
    location: 'Conshohocken, PA',
    m: [56, 60, 56, 56, 58, 54],
    note: 'Supply-chain AI; limited public gen-AI narrative.',
  },
  {
    name: 'IQVIA',
    industry: 'Healthcare',
    founded: 1982,
    revenue: 15400,
    employees: 87000,
    location: 'Durham, NC',
    m: [66, 68, 64, 66, 68, 66],
    note: 'AI in clinical development and real-world data; public "AI-enabled R&D" positioning.',
  },
  {
    name: 'Walgreens Boots Alliance',
    industry: 'Healthcare',
    founded: 1901,
    revenue: 147000,
    employees: 200000,
    location: 'Deerfield, IL',
    m: [50, 54, 50, 50, 54, 48],
    note: 'AI in pharmacy operations; limited public AI strategy amid restructuring.',
  },
  {
    name: 'Danaher',
    industry: 'Healthcare',
    founded: 1969,
    revenue: 23900,
    employees: 63000,
    location: 'Washington, DC',
    m: [64, 66, 62, 64, 68, 62],
    note: 'AI in diagnostics and lab automation; moderate public positioning.',
  },

  // ─────────────────────────────────────────────── RETAIL ───────────────────────────────────────────────
  {
    name: 'Walmart',
    industry: 'Retail',
    founded: 1962,
    revenue: 681000,
    employees: 2100000,
    location: 'Bentonville, AR',
    m: [86, 90, 84, 86, 82, 82],
    featured: true,
    note: 'AI tools rolled out to ~1.5M associates, an OpenAI partnership for AI-first shopping (Oct 2025), and spatial-AI digital twins that detect store issues weeks early; McMillon publicly calls AI the company\'s biggest competitive lever.',
  },
  {
    name: 'Target',
    industry: 'Retail',
    founded: 1902,
    revenue: 107000,
    employees: 415000,
    location: 'Minneapolis, MN',
    m: [72, 76, 70, 72, 72, 70],
    note: 'AI personalization and store operations (Roundel); public comments on gen-AI supply-chain and guest tools.',
  },
  {
    name: 'Home Depot',
    industry: 'Retail',
    founded: 1978,
    revenue: 152000,
    employees: 465000,
    location: 'Atlanta, GA',
    m: [74, 78, 72, 74, 74, 72],
    note: 'HD Sidekick store assistant and AI search; publicly touts gen-AI "online experience" and associate tools.',
  },
  {
    name: "Lowe's",
    industry: 'Retail',
    founded: 1946,
    revenue: 84000,
    employees: 290000,
    location: 'Mooresville, NC',
    m: [68, 72, 66, 68, 70, 66],
    note: 'AI store assistant and planning tools; moderate public AI commentary.',
  },
  {
    name: 'Costco',
    industry: 'Retail',
    founded: 1983,
    revenue: 273000,
    employees: 333000,
    location: 'Issaquah, WA',
    m: [54, 60, 52, 54, 60, 52],
    note: 'Conservative: minimal public gen-AI narrative; uses ML for pricing and membership quietly.',
  },
  {
    name: 'Kroger',
    industry: 'Retail',
    founded: 1883,
    revenue: 148000,
    employees: 430000,
    location: 'Cincinnati, OH',
    m: [62, 66, 62, 62, 64, 60],
    note: '84.51° analytics and AI personalization; public comments on gen-AI in retail media.',
  },
  {
    name: 'Albertsons',
    industry: 'Retail',
    founded: 1939,
    revenue: 79000,
    employees: 290000,
    location: 'Boise, ID',
    m: [58, 62, 58, 58, 60, 56],
    note: 'AI personalization via loyalty; moderate public narrative.',
  },
  {
    name: 'Dollar General',
    industry: 'Retail',
    founded: 1939,
    revenue: 40000,
    employees: 164000,
    location: 'Goodlettsville, TN',
    m: [48, 52, 48, 48, 52, 46],
    note: 'Limited public AI strategy; cost-focused operations.',
  },
  {
    name: 'Dollar Tree',
    industry: 'Retail',
    founded: 1986,
    revenue: 30000,
    employees: 190000,
    location: 'Chesapeake, VA',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Minimal public AI commentary.',
  },
  {
    name: 'Best Buy',
    industry: 'Retail',
    founded: 1966,
    revenue: 41000,
    employees: 85000,
    location: 'Richfield, MN',
    m: [64, 68, 62, 64, 66, 62],
    note: 'AI service/support (Geek Squad) and a gen-AI shopping assistant; moderate public positioning.',
  },
  {
    name: "Macy's",
    industry: 'Retail',
    founded: 1858,
    revenue: 23000,
    employees: 94000,
    location: 'New York, NY',
    m: [52, 56, 50, 52, 56, 50],
    note: 'AI personalization and pricing; limited public gen-AI narrative amid turnaround.',
  },
  {
    name: 'Nordstrom',
    industry: 'Retail',
    founded: 1901,
    revenue: 14500,
    employees: 60000,
    location: 'Seattle, WA',
    m: [52, 56, 50, 52, 56, 50],
    note: 'AI recommendations; limited public gen-AI commentary.',
  },
  {
    name: 'TJX',
    industry: 'Retail',
    founded: 1976,
    revenue: 56400,
    employees: 340000,
    location: 'Framingham, MA',
    m: [48, 52, 48, 48, 52, 46],
    note: 'Off-price model; minimal public AI strategy.',
  },
  {
    name: 'Gap',
    industry: 'Retail',
    founded: 1969,
    revenue: 14900,
    employees: 95000,
    location: 'San Francisco, CA',
    m: [48, 52, 48, 48, 52, 46],
    note: 'AI in personalization; limited public commentary.',
  },
  {
    name: 'eBay',
    industry: 'Retail',
    founded: 1995,
    revenue: 10300,
    employees: 12000,
    location: 'San Jose, CA',
    m: [58, 62, 56, 58, 60, 56],
    note: 'AI listings and search; public comments on gen-AI selling tools for merchants.',
  },
  {
    name: 'Ulta Beauty',
    industry: 'Retail',
    founded: 1990,
    revenue: 11300,
    employees: 50000,
    location: 'Bolingbrook, IL',
    m: [54, 58, 52, 54, 56, 52],
    note: 'AI personalization in retail media; limited public gen-AI narrative.',
  },
  {
    name: 'Ross Stores',
    industry: 'Retail',
    founded: 1982,
    revenue: 21400,
    employees: 100000,
    location: 'Dublin, CA',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Off-price; minimal public AI commentary.',
  },

  // ───────────────────────────────────────────── CONSUMER GOODS ─────────────────────────────────────────────
  {
    name: 'Procter & Gamble',
    industry: 'Consumer Goods',
    founded: 1837,
    revenue: 84000,
    employees: 105000,
    location: 'Cincinnati, OH',
    m: [72, 76, 72, 72, 76, 72],
    note: 'AI across supply chain, marketing and R&D (gen-AI-enabled marketing); public comments on AI-driven productivity.',
  },
  {
    name: 'PepsiCo',
    industry: 'Consumer Goods',
    founded: 1965,
    revenue: 92000,
    employees: 318000,
    location: 'Purchase, NY',
    m: [70, 74, 70, 70, 74, 70],
    note: 'AI in supply chain and sales (PepsiCo Digital); public "AI-powered efficiency" commentary.',
  },
  {
    name: 'Coca-Cola',
    industry: 'Consumer Goods',
    founded: 1892,
    revenue: 47000,
    employees: 80000,
    location: 'Atlanta, GA',
    m: [74, 76, 72, 76, 74, 72],
    note: 'Gen-AI-first marketer (Y3000, AI campaigns, Microsoft partnership); Quincey publicly frames AI as core to creativity and productivity.',
  },
  {
    name: 'Mondelez',
    industry: 'Consumer Goods',
    founded: 2012,
    revenue: 36400,
    employees: 91000,
    location: 'Chicago, IL',
    m: [66, 70, 66, 66, 70, 64],
    note: 'AI in supply chain and marketing; moderate public gen-AI commentary.',
  },
  {
    name: 'General Mills',
    industry: 'Consumer Goods',
    founded: 1928,
    revenue: 19900,
    employees: 25000,
    location: 'Minneapolis, MN',
    m: [62, 66, 62, 62, 66, 60],
    note: 'AI in demand forecasting and R&D; public comments on gen-AI efficiency.',
  },
  {
    name: 'Kraft Heinz',
    industry: 'Consumer Goods',
    founded: 2015,
    revenue: 25800,
    employees: 57000,
    location: 'Pittsburgh, PA',
    m: [58, 62, 58, 58, 62, 56],
    note: 'AI in marketing and supply chain; moderate public narrative.',
  },
  {
    name: 'Starbucks',
    industry: 'Consumer Goods',
    founded: 1971,
    revenue: 36200,
    employees: 402000,
    location: 'Seattle, WA',
    m: [72, 74, 72, 72, 72, 70],
    note: 'Deep Brew AI for personalization and store ops; public comments on gen-AI ordering and personalization.',
  },
  {
    name: "McDonald's",
    industry: 'Consumer Goods',
    founded: 1955,
    revenue: 25900,
    employees: 200000,
    location: 'Chicago, IL',
    m: [68, 70, 68, 70, 68, 66],
    note: 'Google gen-AI partnership (2023) and AI drive-thru/store tools; public AI-efficiency commentary from Kempczinski.',
  },
  {
    name: 'Yum! Brands',
    industry: 'Consumer Goods',
    founded: 1997,
    revenue: 7000,
    employees: 35000,
    location: 'Louisville, KY',
    m: [60, 64, 60, 60, 62, 58],
    note: 'AI ordering and personalization across KFC/Pizza Hut/Taco Bell; moderate public AI narrative.',
  },
  {
    name: 'Nike',
    industry: 'Consumer Goods',
    founded: 1964,
    revenue: 51000,
    employees: 79000,
    location: 'Beaverton, OR',
    m: [62, 66, 62, 62, 64, 60],
    note: 'AI personalization and supply chain; public gen-AI commentary limited amid restructuring.',
  },
  {
    name: 'Philip Morris',
    industry: 'Consumer Goods',
    founded: 1847,
    revenue: 36000,
    employees: 82000,
    location: 'New York, NY',
    m: [66, 70, 66, 66, 70, 64],
    note: 'AI in consumer engagement (IQOS ecosystem); moderate public AI commentary.',
  },
  {
    name: 'Altria',
    industry: 'Consumer Goods',
    founded: 1919,
    revenue: 20000,
    employees: 6300,
    location: 'Richmond, VA',
    m: [48, 52, 48, 48, 52, 46],
    note: 'Limited public AI strategy.',
  },
  {
    name: 'Colgate-Palmolive',
    industry: 'Consumer Goods',
    founded: 1806,
    revenue: 20100,
    employees: 34000,
    location: 'New York, NY',
    m: [56, 60, 56, 56, 60, 54],
    note: 'AI in marketing and supply chain; modest public commentary.',
  },
  {
    name: 'Kimberly-Clark',
    industry: 'Consumer Goods',
    founded: 1872,
    revenue: 20100,
    employees: 43000,
    location: 'Irving, TX',
    m: [54, 58, 54, 54, 58, 52],
    note: 'Supply-chain AI; modest public AI commentary.',
  },
  {
    name: 'Tyson Foods',
    industry: 'Consumer Goods',
    founded: 1935,
    revenue: 53300,
    employees: 139000,
    location: 'Springdale, AR',
    m: [52, 56, 52, 52, 56, 50],
    note: 'AI in production and supply chain; limited public gen-AI narrative.',
  },
  {
    name: 'Estée Lauder',
    industry: 'Consumer Goods',
    founded: 1946,
    revenue: 15600,
    employees: 62000,
    location: 'New York, NY',
    m: [54, 58, 52, 54, 56, 52],
    note: 'AI personalization in retail media; limited public gen-AI amid turnaround.',
  },
  {
    name: 'Hershey',
    industry: 'Consumer Goods',
    founded: 1894,
    revenue: 18500,
    employees: 21000,
    location: 'Hershey, PA',
    m: [56, 60, 54, 56, 58, 54],
    note: 'AI in demand forecasting and marketing; modest public commentary.',
  },
  {
    name: 'Kellanova',
    industry: 'Consumer Goods',
    founded: 2023,
    revenue: 13200,
    employees: 24000,
    location: 'Chicago, IL',
    m: [52, 56, 52, 52, 56, 50],
    note: 'AI in supply chain and marketing; limited public gen-AI narrative.',
  },

  // ─────────────────────────────────────────────── AUTOMOTIVE ───────────────────────────────────────────────
  {
    name: 'Tesla',
    industry: 'Automotive',
    founded: 2003,
    revenue: 98000,
    employees: 121000,
    location: 'Austin, TX',
    m: [80, 78, 74, 86, 66, 84],
    featured: true,
    note: 'FSD/autonomy, Dojo training clusters and Optimus robots; Musk publicly frames Tesla as an AI/robotics company whose value is "almost entirely" tied to autonomy.',
  },
  {
    name: 'General Motors',
    industry: 'Automotive',
    founded: 1908,
    revenue: 187000,
    employees: 163000,
    location: 'Detroit, MI',
    m: [66, 70, 66, 68, 68, 66],
    note: 'Cruise robotaxis and Super Cruise ADAS; public comments on AI in manufacturing and software-defined vehicles.',
  },
  {
    name: 'Ford',
    industry: 'Automotive',
    founded: 1903,
    revenue: 185000,
    employees: 170000,
    location: 'Dearborn, MI',
    m: [64, 68, 64, 66, 66, 64],
    note: 'BlueCruise and AI in manufacturing; moderate public gen-AI commentary.',
  },
  {
    name: 'Toyota Motor North America',
    industry: 'Automotive',
    founded: 1957,
    revenue: 220000,
    employees: 48000,
    location: 'Plano, TX',
    m: [62, 66, 62, 62, 64, 60],
    note: 'Toyota Research Institute and Woven City AI; measured public positioning.',
  },
  {
    name: 'American Honda',
    industry: 'Automotive',
    founded: 1959,
    revenue: 62000,
    employees: 30000,
    location: 'Torrance, CA',
    m: [54, 58, 54, 54, 58, 52],
    note: 'ADAS-focused AI; limited public gen-AI narrative.',
  },
  {
    name: 'Stellantis',
    industry: 'Automotive',
    founded: 2021,
    revenue: 160000,
    employees: 250000,
    location: 'Auburn Hills, MI',
    m: [58, 62, 58, 58, 60, 56],
    note: 'STLA SmartCockpit AI; moderate public commentary.',
  },
  {
    name: 'Cummins',
    industry: 'Automotive',
    founded: 1919,
    revenue: 34100,
    employees: 75000,
    location: 'Columbus, IN',
    m: [60, 64, 60, 60, 62, 58],
    note: 'AI in engine diagnostics and manufacturing; moderate public narrative.',
  },
  {
    name: 'Aptiv',
    industry: 'Automotive',
    founded: 1994,
    revenue: 20100,
    employees: 155000,
    location: 'Dublin, IE',
    m: [60, 62, 58, 62, 60, 60],
    note: 'AI in ADAS and software-defined vehicles; public tech-forward positioning.',
  },
  {
    name: 'Magna',
    industry: 'Automotive',
    founded: 1957,
    revenue: 42800,
    employees: 174000,
    location: 'Aurora, ON',
    m: [56, 60, 56, 56, 58, 54],
    note: 'AI in manufacturing and ADAS; limited public gen-AI narrative.',
  },
  {
    name: 'Lear',
    industry: 'Automotive',
    founded: 1917,
    revenue: 23300,
    employees: 170000,
    location: 'Southfield, MI',
    m: [48, 52, 48, 48, 52, 46],
    note: 'Minimal public AI commentary.',
  },
  {
    name: 'BorgWarner',
    industry: 'Automotive',
    founded: 1928,
    revenue: 14100,
    employees: 40000,
    location: 'Auburn Hills, MI',
    m: [50, 54, 50, 50, 54, 48],
    note: 'Limited public AI strategy.',
  },

  // ─────────────────────────────────────────── AEROSPACE & DEFENSE ───────────────────────────────────────────
  {
    name: 'GE Aerospace',
    industry: 'Aerospace & Defense',
    founded: 1892,
    revenue: 38200,
    employees: 55000,
    location: 'Evendale, OH',
    m: [74, 76, 72, 74, 74, 72],
    note: 'AI engine diagnostics and maintenance; public comments on digital twins and AI in aviation services.',
  },
  {
    name: 'Boeing',
    industry: 'Aerospace & Defense',
    founded: 1916,
    revenue: 66500,
    employees: 171000,
    location: 'Arlington, VA',
    m: [56, 60, 56, 56, 60, 54],
    note: 'AI in manufacturing and quality; public AI commentary subdued amid the operational crisis.',
  },
  {
    name: 'Lockheed Martin',
    industry: 'Aerospace & Defense',
    founded: 1912,
    revenue: 71000,
    employees: 122000,
    location: 'Bethesda, MD',
    m: [66, 68, 64, 66, 68, 66],
    note: 'AI for defense (JADC2, autonomy); public AI-first defense positioning.',
  },
  {
    name: 'RTX',
    industry: 'Aerospace & Defense',
    founded: 1922,
    revenue: 80700,
    employees: 185000,
    location: 'Arlington, VA',
    m: [64, 66, 62, 64, 66, 64],
    note: 'AI in defense and aviation; moderate public AI commentary.',
  },
  {
    name: 'Northrop Grumman',
    industry: 'Aerospace & Defense',
    founded: 1939,
    revenue: 41000,
    employees: 98000,
    location: 'Falls Church, VA',
    m: [62, 64, 60, 62, 64, 62],
    note: 'AI in autonomy and space; public AI defense positioning.',
  },
  {
    name: 'General Dynamics',
    industry: 'Aerospace & Defense',
    founded: 1899,
    revenue: 47700,
    employees: 111000,
    location: 'Reston, VA',
    m: [60, 62, 58, 60, 62, 58],
    note: 'AI in shipbuilding and IT; measured public commentary.',
  },
  {
    name: 'L3Harris',
    industry: 'Aerospace & Defense',
    founded: 2019,
    revenue: 21200,
    employees: 54000,
    location: 'Melbourne, FL',
    m: [58, 60, 56, 58, 60, 56],
    note: 'AI in ISR and defense electronics; moderate public AI narrative.',
  },
  {
    name: 'Textron',
    industry: 'Aerospace & Defense',
    founded: 1923,
    revenue: 13700,
    employees: 35000,
    location: 'Providence, RI',
    m: [52, 56, 52, 52, 56, 50],
    note: 'Limited public AI commentary.',
  },

  // ─────────────────────────────────────────── ENERGY & UTILITIES ───────────────────────────────────────────
  {
    name: 'ExxonMobil',
    industry: 'Energy & Utilities',
    founded: 1870,
    revenue: 339000,
    employees: 62000,
    location: 'Spring, TX',
    m: [62, 66, 62, 62, 66, 60],
    note: 'AI in reservoir modeling and operations; public comments on AI productivity and AI-driven power demand.',
  },
  {
    name: 'Chevron',
    industry: 'Energy & Utilities',
    founded: 1879,
    revenue: 200000,
    employees: 45000,
    location: 'San Ramon, CA',
    m: [60, 64, 60, 60, 64, 58],
    note: 'AI in operations and safety; moderate public AI commentary.',
  },
  {
    name: 'ConocoPhillips',
    industry: 'Energy & Utilities',
    founded: 1917,
    revenue: 56300,
    employees: 11000,
    location: 'Houston, TX',
    m: [52, 56, 52, 52, 56, 50],
    note: 'AI in subsurface modeling; limited public gen-AI narrative.',
  },
  {
    name: 'SLB',
    industry: 'Energy & Utilities',
    founded: 1926,
    revenue: 36300,
    employees: 96000,
    location: 'Houston, TX',
    m: [70, 74, 68, 70, 72, 70],
    note: 'AI in oilfield operations (Lumi data platform); public "AI-driven energy" positioning.',
  },
  {
    name: 'Baker Hughes',
    industry: 'Energy & Utilities',
    founded: 1907,
    revenue: 27500,
    employees: 58000,
    location: 'Houston, TX',
    m: [64, 68, 64, 64, 66, 62],
    note: 'Cordant asset-intelligence AI; moderate public AI narrative.',
  },
  {
    name: 'Halliburton',
    industry: 'Energy & Utilities',
    founded: 1919,
    revenue: 23200,
    employees: 60000,
    location: 'Houston, TX',
    m: [56, 60, 56, 56, 60, 54],
    note: 'AI in drilling operations (DecisionSpace); limited public gen-AI commentary.',
  },
  {
    name: 'Phillips 66',
    industry: 'Energy & Utilities',
    founded: 1875,
    revenue: 139000,
    employees: 13000,
    location: 'Houston, TX',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Limited public AI strategy; refining.',
  },
  {
    name: 'Valero Energy',
    industry: 'Energy & Utilities',
    founded: 1980,
    revenue: 140000,
    employees: 10000,
    location: 'San Antonio, TX',
    m: [44, 48, 44, 44, 48, 42],
    note: 'Minimal public AI commentary; refining.',
  },
  {
    name: 'Marathon Petroleum',
    industry: 'Energy & Utilities',
    founded: 1887,
    revenue: 147000,
    employees: 17000,
    location: 'Findlay, OH',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Minimal public AI commentary.',
  },
  {
    name: 'Occidental Petroleum',
    industry: 'Energy & Utilities',
    founded: 1920,
    revenue: 27600,
    employees: 11000,
    location: 'Houston, TX',
    m: [50, 54, 50, 50, 54, 48],
    note: 'AI in carbon capture/operations (1PointFive); limited public gen-AI narrative.',
  },
  {
    name: 'NextEra Energy',
    industry: 'Energy & Utilities',
    founded: 1984,
    revenue: 25100,
    employees: 16000,
    location: 'Juno Beach, FL',
    m: [54, 58, 54, 54, 58, 52],
    note: 'AI in grid operations and renewables forecasting; moderate public commentary.',
  },
  {
    name: 'Duke Energy',
    industry: 'Energy & Utilities',
    founded: 1904,
    revenue: 29500,
    employees: 28000,
    location: 'Charlotte, NC',
    m: [50, 54, 50, 50, 54, 48],
    note: 'AI in grid management; limited public gen-AI narrative.',
  },
  {
    name: 'Southern Company',
    industry: 'Energy & Utilities',
    founded: 1945,
    revenue: 25600,
    employees: 28000,
    location: 'Atlanta, GA',
    m: [48, 52, 48, 48, 52, 46],
    note: 'AI in grid and plant operations; limited public AI commentary.',
  },
  {
    name: 'Dominion Energy',
    industry: 'Energy & Utilities',
    founded: 1983,
    revenue: 14800,
    employees: 17000,
    location: 'Richmond, VA',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Limited public AI commentary.',
  },
  {
    name: 'Entergy',
    industry: 'Energy & Utilities',
    founded: 1913,
    revenue: 13500,
    employees: 13000,
    location: 'New Orleans, LA',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Public commentary centers on AI data-center power demand; limited internal AI narrative.',
  },
  {
    name: 'Freeport-McMoRan',
    industry: 'Energy & Utilities',
    founded: 1912,
    revenue: 25400,
    employees: 27000,
    location: 'Phoenix, AZ',
    m: [52, 56, 52, 52, 56, 50],
    note: 'AI in mining operations (autonomous haulage); limited public gen-AI.',
  },
  {
    name: 'Newmont',
    industry: 'Energy & Utilities',
    founded: 1921,
    revenue: 18700,
    employees: 32000,
    location: 'Denver, CO',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Autonomous mining AI; limited public commentary.',
  },

  // ─────────────────────────────────────── INDUSTRIAL & MANUFACTURING ───────────────────────────────────────
  {
    name: 'Honeywell',
    industry: 'Industrial & Manufacturing',
    founded: 1906,
    revenue: 39000,
    employees: 96000,
    location: 'Charlotte, NC',
    m: [72, 76, 72, 72, 74, 72],
    note: 'Explicit AI strategy across aerospace, buildings and industrial automation; public statements on AI agents and OT+IT convergence (Honeywell Forge).',
  },
  {
    name: 'Deere',
    industry: 'Industrial & Manufacturing',
    founded: 1837,
    revenue: 44000,
    employees: 82000,
    location: 'Moline, IL',
    m: [66, 72, 68, 66, 68, 64],
    note: 'Autonomous tractors, See & Spray and precision-ag AI; public AI-first agriculture positioning.',
  },
  {
    name: 'Caterpillar',
    industry: 'Industrial & Manufacturing',
    founded: 1925,
    revenue: 67000,
    employees: 113000,
    location: 'Irving, TX',
    m: [58, 62, 58, 58, 62, 56],
    note: 'Autonomous mining and trucking AI; measured public AI commentary.',
  },
  {
    name: '3M',
    industry: 'Industrial & Manufacturing',
    founded: 1902,
    revenue: 32000,
    employees: 85000,
    location: 'St. Paul, MN',
    m: [60, 64, 60, 60, 64, 58],
    note: 'AI in R&D and manufacturing; moderate public commentary.',
  },
  {
    name: 'Emerson',
    industry: 'Industrial & Manufacturing',
    founded: 1890,
    revenue: 18000,
    employees: 72000,
    location: 'St. Louis, MO',
    m: [60, 64, 60, 60, 62, 58],
    note: 'Industrial-automation AI (AspenTech); moderate public narrative.',
  },
  {
    name: 'Rockwell Automation',
    industry: 'Industrial & Manufacturing',
    founded: 1903,
    revenue: 9000,
    employees: 28000,
    location: 'Milwaukee, WI',
    m: [64, 66, 64, 64, 64, 62],
    note: 'Factory AI and industrial analytics; public "connected enterprise" AI positioning.',
  },
  {
    name: 'Eaton',
    industry: 'Industrial & Manufacturing',
    founded: 1911,
    revenue: 24000,
    employees: 94000,
    location: 'Dublin, IE',
    m: [60, 62, 58, 60, 62, 58],
    note: 'AI in power management and grid; moderate public commentary.',
  },
  {
    name: 'Parker Hannifin',
    industry: 'Industrial & Manufacturing',
    founded: 1917,
    revenue: 20000,
    employees: 61000,
    location: 'Cleveland, OH',
    m: [56, 60, 56, 56, 60, 54],
    note: 'Modest public AI commentary.',
  },
  {
    name: 'Johnson Controls',
    industry: 'Industrial & Manufacturing',
    founded: 1885,
    revenue: 23000,
    employees: 100000,
    location: 'Cork, IE',
    m: [62, 66, 62, 62, 64, 60],
    note: 'AI in smart buildings (OpenBlue); public "AI for buildings" positioning.',
  },
  {
    name: 'Dow',
    industry: 'Industrial & Manufacturing',
    founded: 1897,
    revenue: 43000,
    employees: 36000,
    location: 'Midland, MI',
    m: [58, 62, 58, 58, 62, 56],
    note: 'AI in R&D and manufacturing; moderate public commentary.',
  },
  {
    name: 'DuPont',
    industry: 'Industrial & Manufacturing',
    founded: 1802,
    revenue: 12000,
    employees: 24000,
    location: 'Wilmington, DE',
    m: [54, 58, 54, 54, 58, 52],
    note: 'AI in materials R&D; limited public gen-AI narrative.',
  },
  {
    name: 'LyondellBasell',
    industry: 'Industrial & Manufacturing',
    founded: 2007,
    revenue: 41000,
    employees: 19000,
    location: 'Houston, TX',
    m: [50, 54, 50, 50, 54, 48],
    note: 'Limited public AI commentary.',
  },
  {
    name: 'Linde',
    industry: 'Industrial & Manufacturing',
    founded: 1879,
    revenue: 33000,
    employees: 66000,
    location: 'Guildford, UK',
    m: [56, 60, 56, 56, 60, 54],
    note: 'AI in operations and safety; moderate public commentary.',
  },
  {
    name: 'PPG Industries',
    industry: 'Industrial & Manufacturing',
    founded: 1883,
    revenue: 18000,
    employees: 52000,
    location: 'Pittsburgh, PA',
    m: [50, 54, 50, 50, 54, 48],
    note: 'Limited public AI commentary.',
  },
  {
    name: 'Illinois Tool Works',
    industry: 'Industrial & Manufacturing',
    founded: 1912,
    revenue: 16000,
    employees: 44000,
    location: 'Glenview, IL',
    m: [46, 50, 46, 46, 50, 44],
    note: 'Minimal public AI narrative.',
  },
  {
    name: 'GE Vernova',
    industry: 'Industrial & Manufacturing',
    founded: 2024,
    revenue: 35000,
    employees: 85000,
    location: 'Cambridge, MA',
    m: [56, 60, 56, 56, 60, 54],
    note: 'AI in grid and electrification; public commentary on AI-driven power demand.',
  },
  {
    name: 'Whirlpool',
    industry: 'Industrial & Manufacturing',
    founded: 1911,
    revenue: 19000,
    employees: 59000,
    location: 'Benton Harbor, MI',
    m: [50, 54, 50, 50, 54, 48],
    note: 'Limited public AI commentary; connected appliances.',
  },
  {
    name: 'Carrier Global',
    industry: 'Industrial & Manufacturing',
    founded: 2020,
    revenue: 22000,
    employees: 58000,
    location: 'Palm Beach Gardens, FL',
    m: [58, 62, 58, 58, 60, 56],
    note: 'AI in HVAC and building services; moderate public commentary.',
  },

  // ──────────────────────────────────── TRANSPORTATION & LOGISTICS ────────────────────────────────────
  {
    name: 'FedEx',
    industry: 'Transportation & Logistics',
    founded: 1971,
    revenue: 87000,
    employees: 500000,
    location: 'Memphis, TN',
    m: [72, 76, 72, 72, 72, 70],
    note: 'AI in routing and operations (FedEx Dataworks); public comments on gen-AI for customer service and network optimization.',
  },
  {
    name: 'UPS',
    industry: 'Transportation & Logistics',
    founded: 1907,
    revenue: 91000,
    employees: 500000,
    location: 'Atlanta, GA',
    m: [70, 74, 70, 70, 70, 68],
    note: 'ORION route optimization plus AI; public comments (Tomé) on AI-driven network efficiency.',
  },
  {
    name: 'Uber',
    industry: 'Transportation & Logistics',
    founded: 2009,
    revenue: 44000,
    employees: 32000,
    location: 'San Francisco, CA',
    m: [72, 76, 70, 74, 68, 74],
    note: 'AI-native dispatch and pricing; public gen-AI support tools and customer-service agents.',
  },
  {
    name: 'Delta Air Lines',
    industry: 'Transportation & Logistics',
    founded: 1924,
    revenue: 62000,
    employees: 100000,
    location: 'Atlanta, GA',
    m: [62, 66, 62, 62, 64, 60],
    note: 'AI in operations (baggage, predictive maintenance); moderate public AI commentary.',
  },
  {
    name: 'United Airlines',
    industry: 'Transportation & Logistics',
    founded: 1926,
    revenue: 57000,
    employees: 100000,
    location: 'Chicago, IL',
    m: [60, 64, 60, 60, 62, 58],
    note: 'AI in operations and crew scheduling; moderate public narrative.',
  },
  {
    name: 'American Airlines',
    industry: 'Transportation & Logistics',
    founded: 1930,
    revenue: 55000,
    employees: 130000,
    location: 'Fort Worth, TX',
    m: [58, 62, 58, 58, 60, 56],
    note: 'AI in operations and revenue management; measured public commentary.',
  },
  {
    name: 'Southwest Airlines',
    industry: 'Transportation & Logistics',
    founded: 1967,
    revenue: 27000,
    employees: 74000,
    location: 'Dallas, TX',
    m: [56, 60, 56, 56, 58, 54],
    note: 'Limited public AI narrative; operational focus.',
  },
  {
    name: 'Union Pacific',
    industry: 'Transportation & Logistics',
    founded: 1862,
    revenue: 24000,
    employees: 32000,
    location: 'Omaha, NE',
    m: [60, 62, 60, 60, 62, 58],
    note: 'AI in rail operations (autonomous inspection); moderate public commentary.',
  },
  {
    name: 'CSX',
    industry: 'Transportation & Logistics',
    founded: 1980,
    revenue: 15000,
    employees: 21000,
    location: 'Jacksonville, FL',
    m: [56, 60, 56, 56, 58, 54],
    note: 'AI in rail operations; moderate public commentary.',
  },
  {
    name: 'Norfolk Southern',
    industry: 'Transportation & Logistics',
    founded: 1881,
    revenue: 12000,
    employees: 19000,
    location: 'Atlanta, GA',
    m: [54, 58, 54, 54, 56, 52],
    note: 'AI in rail operations; limited public gen-AI narrative.',
  },
  {
    name: 'J.B. Hunt',
    industry: 'Transportation & Logistics',
    founded: 1961,
    revenue: 13000,
    employees: 33000,
    location: 'Lowell, AR',
    m: [58, 62, 58, 58, 60, 56],
    note: 'Autonomous-trucking pilots and AI routing; moderate public narrative.',
  },
  {
    name: 'C.H. Robinson',
    industry: 'Transportation & Logistics',
    founded: 1905,
    revenue: 18000,
    employees: 15000,
    location: 'Eden Prairie, MN',
    m: [56, 60, 56, 56, 58, 54],
    note: 'AI freight brokerage (Navisphere); moderate public narrative.',
  },

  // ─────────────────────────────────────────────── TELECOM & MEDIA ───────────────────────────────────────────────
  {
    name: 'Verizon',
    industry: 'Telecom & Media',
    founded: 1983,
    revenue: 135000,
    employees: 105000,
    location: 'New York, NY',
    m: [68, 72, 66, 68, 70, 66],
    note: 'AI in network operations and customer service; public statements on gen-AI agents and network AI.',
  },
  {
    name: 'AT&T',
    industry: 'Telecom & Media',
    founded: 1885,
    revenue: 122000,
    employees: 149000,
    location: 'Dallas, TX',
    m: [66, 70, 66, 66, 68, 64],
    note: 'AI in network automation; public "AI-powered network" commentary with moderate gen-AI.',
  },
  {
    name: 'T-Mobile',
    industry: 'Telecom & Media',
    founded: 1994,
    revenue: 82000,
    employees: 71000,
    location: 'Bellevue, WA',
    m: [70, 72, 68, 70, 70, 68],
    note: 'T-AI / gen-AI customer service; public AI-first service positioning.',
  },
  {
    name: 'Comcast',
    industry: 'Telecom & Media',
    founded: 1963,
    revenue: 122000,
    employees: 186000,
    location: 'Philadelphia, PA',
    m: [64, 68, 64, 64, 66, 62],
    note: 'AI in connectivity and Xfinity; moderate public commentary.',
  },
  {
    name: 'Charter',
    industry: 'Telecom & Media',
    founded: 1993,
    revenue: 55000,
    employees: 101000,
    location: 'Stamford, CT',
    m: [60, 64, 60, 60, 62, 58],
    note: 'AI in network operations; limited public gen-AI narrative.',
  },
  {
    name: 'Disney',
    industry: 'Telecom & Media',
    founded: 1923,
    revenue: 91000,
    employees: 200000,
    location: 'Burbank, CA',
    m: [58, 62, 56, 58, 60, 56],
    note: 'AI in streaming recommendation and gen-AI production debates; publicly balanced posture from Iger.',
  },
  {
    name: 'Netflix',
    industry: 'Telecom & Media',
    founded: 1997,
    revenue: 44000,
    employees: 14000,
    location: 'Los Gatos, CA',
    m: [64, 72, 60, 68, 62, 68],
    note: 'ML-driven recommendation is core; public comments treat AI as an efficiency tool in content production, not a headline strategy.',
  },
  {
    name: 'Warner Bros. Discovery',
    industry: 'Telecom & Media',
    founded: 2022,
    revenue: 41000,
    employees: 37000,
    location: 'New York, NY',
    m: [50, 54, 48, 50, 52, 48],
    note: 'AI in streaming; limited public gen-AI narrative amid debt reduction.',
  },
  {
    name: 'Paramount',
    industry: 'Telecom & Media',
    founded: 2005,
    revenue: 29000,
    employees: 22000,
    location: 'New York, NY',
    m: [48, 52, 48, 48, 52, 46],
    note: 'Limited public AI commentary; pending merger context.',
  },
  {
    name: 'Fox',
    industry: 'Telecom & Media',
    founded: 2019,
    revenue: 14400,
    employees: 10000,
    location: 'New York, NY',
    m: [52, 56, 50, 52, 54, 50],
    note: 'AI in streaming (Tubi) and production; moderate public commentary.',
  },
  {
    name: 'News Corp',
    industry: 'Telecom & Media',
    founded: 2013,
    revenue: 10100,
    employees: 24000,
    location: 'New York, NY',
    m: [50, 54, 48, 50, 52, 48],
    note: 'AI content-licensing deals (e.g. OpenAI); public commentary on AI licensing economics.',
  },
];

/** Number of curated enterprises — the galaxy renders exactly this many stars. */
export const COMPANY_COUNT = FORTUNE500_AI_COMPANIES.length;

// ---------------------------------------------------------------------------
// Company identity meta (ticker + website domain), keyed by exact dataset name.
// Used for the profile header (logo fetch, ticker chip, website link).
// ---------------------------------------------------------------------------

export const COMPANY_META: Record<string, { ticker: string; domain: string }> = {
  Nvidia: { ticker: 'NVDA', domain: 'nvidia.com' },
  Microsoft: { ticker: 'MSFT', domain: 'microsoft.com' },
  Alphabet: { ticker: 'GOOGL', domain: 'abc.xyz' },
  Amazon: { ticker: 'AMZN', domain: 'amazon.com' },
  Meta: { ticker: 'META', domain: 'meta.com' },
  Oracle: { ticker: 'ORCL', domain: 'oracle.com' },
  Broadcom: { ticker: 'AVGO', domain: 'broadcom.com' },
  Palantir: { ticker: 'PLTR', domain: 'palantir.com' },
  ServiceNow: { ticker: 'NOW', domain: 'servicenow.com' },
  Salesforce: { ticker: 'CRM', domain: 'salesforce.com' },
  Accenture: { ticker: 'ACN', domain: 'accenture.com' },
  Adobe: { ticker: 'ADBE', domain: 'adobe.com' },
  AMD: { ticker: 'AMD', domain: 'amd.com' },
  Cisco: { ticker: 'CSCO', domain: 'cisco.com' },
  IBM: { ticker: 'IBM', domain: 'ibm.com' },
  'Dell Technologies': { ticker: 'DELL', domain: 'dell.com' },
  'Hewlett Packard Enterprise': { ticker: 'HPE', domain: 'hpe.com' },
  Intel: { ticker: 'INTC', domain: 'intel.com' },
  Qualcomm: { ticker: 'QCOM', domain: 'qualcomm.com' },
  Micron: { ticker: 'MU', domain: 'micron.com' },
  Apple: { ticker: 'AAPL', domain: 'apple.com' },
  Intuit: { ticker: 'INTU', domain: 'intuit.com' },
  Workday: { ticker: 'WDAY', domain: 'workday.com' },
  'Palo Alto Networks': { ticker: 'PANW', domain: 'paloaltonetworks.com' },
  Cognizant: { ticker: 'CTSH', domain: 'cognizant.com' },
  'Applied Materials': { ticker: 'AMAT', domain: 'appliedmaterials.com' },
  'HP Inc': { ticker: 'HPQ', domain: 'hp.com' },
  'Western Digital': { ticker: 'WDC', domain: 'westerndigital.com' },
  'Texas Instruments': { ticker: 'TXN', domain: 'ti.com' },
  'Motorola Solutions': { ticker: 'MSI', domain: 'motorolasolutions.com' },
  'JPMorgan Chase': { ticker: 'JPM', domain: 'jpmorganchase.com' },
  'Goldman Sachs': { ticker: 'GS', domain: 'goldmansachs.com' },
  'Morgan Stanley': { ticker: 'MS', domain: 'morganstanley.com' },
  'Bank of America': { ticker: 'BAC', domain: 'bankofamerica.com' },
  Citigroup: { ticker: 'C', domain: 'citigroup.com' },
  'Wells Fargo': { ticker: 'WFC', domain: 'wellsfargo.com' },
  'American Express': { ticker: 'AXP', domain: 'americanexpress.com' },
  'Capital One': { ticker: 'COF', domain: 'capitalone.com' },
  Visa: { ticker: 'V', domain: 'visa.com' },
  Mastercard: { ticker: 'MA', domain: 'mastercard.com' },
  PayPal: { ticker: 'PYPL', domain: 'paypal.com' },
  BlackRock: { ticker: 'BLK', domain: 'blackrock.com' },
  'Charles Schwab': { ticker: 'SCHW', domain: 'schwab.com' },
  'BNY Mellon': { ticker: 'BK', domain: 'bnymellon.com' },
  'State Street': { ticker: 'STT', domain: 'statestreet.com' },
  'US Bancorp': { ticker: 'USB', domain: 'usbank.com' },
  'PNC Financial': { ticker: 'PNC', domain: 'pnc.com' },
  Truist: { ticker: 'TFC', domain: 'truist.com' },
  'Intercontinental Exchange': { ticker: 'ICE', domain: 'ice.com' },
  'S&P Global': { ticker: 'SPGI', domain: 'spglobal.com' },
  Fiserv: { ticker: 'FI', domain: 'fiserv.com' },
  FIS: { ticker: 'FIS', domain: 'fisglobal.com' },
  'Berkshire Hathaway': { ticker: 'BRK.B', domain: 'berkshirehathaway.com' },
  Progressive: { ticker: 'PGR', domain: 'progressive.com' },
  Allstate: { ticker: 'ALL', domain: 'allstate.com' },
  Chubb: { ticker: 'CB', domain: 'chubb.com' },
  Travelers: { ticker: 'TRV', domain: 'travelers.com' },
  MetLife: { ticker: 'MET', domain: 'metlife.com' },
  'Prudential Financial': { ticker: 'PRU', domain: 'prudential.com' },
  AIG: { ticker: 'AIG', domain: 'aig.com' },
  'Liberty Mutual': { ticker: '', domain: 'libertymutual.com' }, // mutual — no public ticker
  'The Hartford': { ticker: 'HIG', domain: 'thehartford.com' },
  'UnitedHealth Group': { ticker: 'UNH', domain: 'unitedhealthgroup.com' },
  'Eli Lilly': { ticker: 'LLY', domain: 'lilly.com' },
  Pfizer: { ticker: 'PFE', domain: 'pfizer.com' },
  'Johnson & Johnson': { ticker: 'JNJ', domain: 'jnj.com' },
  Merck: { ticker: 'MRK', domain: 'merck.com' },
  'Abbott Laboratories': { ticker: 'ABT', domain: 'abbott.com' },
  Amgen: { ticker: 'AMGN', domain: 'amgen.com' },
  Medtronic: { ticker: 'MDT', domain: 'medtronic.com' },
  'Boston Scientific': { ticker: 'BSX', domain: 'bostonscientific.com' },
  Stryker: { ticker: 'SYK', domain: 'stryker.com' },
  'CVS Health': { ticker: 'CVS', domain: 'cvshealth.com' },
  'Cigna Group': { ticker: 'CI', domain: 'thecignagroup.com' },
  Humana: { ticker: 'HUM', domain: 'humana.com' },
  'Elevance Health': { ticker: 'ELV', domain: 'elevancehealth.com' },
  Centene: { ticker: 'CNC', domain: 'centene.com' },
  'HCA Healthcare': { ticker: 'HCA', domain: 'hcahealthcare.com' },
  McKesson: { ticker: 'MCK', domain: 'mckesson.com' },
  'Cardinal Health': { ticker: 'CAH', domain: 'cardinalhealth.com' },
  Cencora: { ticker: 'COR', domain: 'cencora.com' },
  IQVIA: { ticker: 'IQV', domain: 'iqvia.com' },
  'Walgreens Boots Alliance': { ticker: 'WBA', domain: 'walgreensbootsalliance.com' },
  Danaher: { ticker: 'DHR', domain: 'danaher.com' },
  Walmart: { ticker: 'WMT', domain: 'walmart.com' },
  Target: { ticker: 'TGT', domain: 'target.com' },
  'Home Depot': { ticker: 'HD', domain: 'homedepot.com' },
  "Lowe's": { ticker: 'LOW', domain: 'lowes.com' },
  Costco: { ticker: 'COST', domain: 'costco.com' },
  Kroger: { ticker: 'KR', domain: 'kroger.com' },
  Albertsons: { ticker: 'ACI', domain: 'albertsons.com' },
  'Dollar General': { ticker: 'DG', domain: 'dollargeneral.com' },
  'Dollar Tree': { ticker: 'DLTR', domain: 'dollartree.com' },
  'Best Buy': { ticker: 'BBY', domain: 'bestbuy.com' },
  "Macy's": { ticker: 'M', domain: 'macys.com' },
  Nordstrom: { ticker: 'JWN', domain: 'nordstrom.com' },
  TJX: { ticker: 'TJX', domain: 'tjx.com' },
  Gap: { ticker: 'GPS', domain: 'gapinc.com' },
  eBay: { ticker: 'EBAY', domain: 'ebay.com' },
  'Ulta Beauty': { ticker: 'ULTA', domain: 'ultabeauty.com' },
  'Ross Stores': { ticker: 'ROST', domain: 'rossstores.com' },
  'Procter & Gamble': { ticker: 'PG', domain: 'pg.com' },
  PepsiCo: { ticker: 'PEP', domain: 'pepsico.com' },
  'Coca-Cola': { ticker: 'KO', domain: 'coca-cola.com' },
  Mondelez: { ticker: 'MDLZ', domain: 'mondelez.com' },
  'General Mills': { ticker: 'GIS', domain: 'generalmills.com' },
  'Kraft Heinz': { ticker: 'KHC', domain: 'kraftheinzcompany.com' },
  Starbucks: { ticker: 'SBUX', domain: 'starbucks.com' },
  "McDonald's": { ticker: 'MCD', domain: 'mcdonalds.com' },
  'Yum! Brands': { ticker: 'YUM', domain: 'yum.com' },
  Nike: { ticker: 'NKE', domain: 'nike.com' },
  'Philip Morris': { ticker: 'PM', domain: 'pmi.com' },
  Altria: { ticker: 'MO', domain: 'altria.com' },
  'Colgate-Palmolive': { ticker: 'CL', domain: 'colgatepalmolive.com' },
  'Kimberly-Clark': { ticker: 'KMB', domain: 'kimberly-clark.com' },
  'Tyson Foods': { ticker: 'TSN', domain: 'tysonfoods.com' },
  'Estée Lauder': { ticker: 'EL', domain: 'elcompanies.com' },
  Hershey: { ticker: 'HSY', domain: 'thehersheycompany.com' },
  Kellanova: { ticker: 'K', domain: 'kellanova.com' },
  Tesla: { ticker: 'TSLA', domain: 'tesla.com' },
  'General Motors': { ticker: 'GM', domain: 'gm.com' },
  Ford: { ticker: 'F', domain: 'ford.com' },
  'Toyota Motor North America': { ticker: 'TM', domain: 'toyota.com' },
  'American Honda': { ticker: 'HMC', domain: 'honda.com' },
  Stellantis: { ticker: 'STLA', domain: 'stellantis.com' },
  Cummins: { ticker: 'CMI', domain: 'cummins.com' },
  Aptiv: { ticker: 'APTV', domain: 'aptiv.com' },
  Magna: { ticker: 'MGA', domain: 'magna.com' },
  Lear: { ticker: 'LEA', domain: 'lear.com' },
  BorgWarner: { ticker: 'BWA', domain: 'borgwarner.com' },
  'GE Aerospace': { ticker: 'GE', domain: 'geaerospace.com' },
  Boeing: { ticker: 'BA', domain: 'boeing.com' },
  'Lockheed Martin': { ticker: 'LMT', domain: 'lockheedmartin.com' },
  RTX: { ticker: 'RTX', domain: 'rtx.com' },
  'Northrop Grumman': { ticker: 'NOC', domain: 'northropgrumman.com' },
  'General Dynamics': { ticker: 'GD', domain: 'gd.com' },
  L3Harris: { ticker: 'LHX', domain: 'l3harris.com' },
  Textron: { ticker: 'TXT', domain: 'textron.com' },
  ExxonMobil: { ticker: 'XOM', domain: 'exxonmobil.com' },
  Chevron: { ticker: 'CVX', domain: 'chevron.com' },
  ConocoPhillips: { ticker: 'COP', domain: 'conocophillips.com' },
  SLB: { ticker: 'SLB', domain: 'slb.com' },
  'Baker Hughes': { ticker: 'BKR', domain: 'bakerhughes.com' },
  Halliburton: { ticker: 'HAL', domain: 'halliburton.com' },
  'Phillips 66': { ticker: 'PSX', domain: 'phillips66.com' },
  'Valero Energy': { ticker: 'VLO', domain: 'valero.com' },
  'Marathon Petroleum': { ticker: 'MPC', domain: 'marathonpetroleum.com' },
  'Occidental Petroleum': { ticker: 'OXY', domain: 'oxy.com' },
  'NextEra Energy': { ticker: 'NEE', domain: 'nexteraenergy.com' },
  'Duke Energy': { ticker: 'DUK', domain: 'duke-energy.com' },
  'Southern Company': { ticker: 'SO', domain: 'southerncompany.com' },
  'Dominion Energy': { ticker: 'D', domain: 'dominionenergy.com' },
  Entergy: { ticker: 'ETR', domain: 'entergy.com' },
  'Freeport-McMoRan': { ticker: 'FCX', domain: 'fcx.com' },
  Newmont: { ticker: 'NEM', domain: 'newmont.com' },
  Honeywell: { ticker: 'HON', domain: 'honeywell.com' },
  Deere: { ticker: 'DE', domain: 'deere.com' },
  Caterpillar: { ticker: 'CAT', domain: 'caterpillar.com' },
  '3M': { ticker: 'MMM', domain: '3m.com' },
  Emerson: { ticker: 'EMR', domain: 'emerson.com' },
  'Rockwell Automation': { ticker: 'ROK', domain: 'rockwellautomation.com' },
  Eaton: { ticker: 'ETN', domain: 'eaton.com' },
  'Parker Hannifin': { ticker: 'PH', domain: 'parker.com' },
  'Johnson Controls': { ticker: 'JCI', domain: 'johnsoncontrols.com' },
  Dow: { ticker: 'DOW', domain: 'dow.com' },
  DuPont: { ticker: 'DD', domain: 'dupont.com' },
  LyondellBasell: { ticker: 'LYB', domain: 'lyondellbasell.com' },
  Linde: { ticker: 'LIN', domain: 'linde.com' },
  'PPG Industries': { ticker: 'PPG', domain: 'ppg.com' },
  'Illinois Tool Works': { ticker: 'ITW', domain: 'itw.com' },
  'GE Vernova': { ticker: 'GEV', domain: 'gevernova.com' },
  Whirlpool: { ticker: 'WHR', domain: 'whirlpoolcorp.com' },
  'Carrier Global': { ticker: 'CARR', domain: 'carrier.com' },
  FedEx: { ticker: 'FDX', domain: 'fedex.com' },
  UPS: { ticker: 'UPS', domain: 'ups.com' },
  Uber: { ticker: 'UBER', domain: 'uber.com' },
  'Delta Air Lines': { ticker: 'DAL', domain: 'delta.com' },
  'United Airlines': { ticker: 'UAL', domain: 'united.com' },
  'American Airlines': { ticker: 'AAL', domain: 'aa.com' },
  'Southwest Airlines': { ticker: 'LUV', domain: 'southwest.com' },
  'Union Pacific': { ticker: 'UNP', domain: 'up.com' },
  CSX: { ticker: 'CSX', domain: 'csx.com' },
  'Norfolk Southern': { ticker: 'NSC', domain: 'nscorp.com' },
  'J.B. Hunt': { ticker: 'JBHT', domain: 'jbhunt.com' },
  'C.H. Robinson': { ticker: 'CHRW', domain: 'chrobinson.com' },
  Verizon: { ticker: 'VZ', domain: 'verizon.com' },
  'AT&T': { ticker: 'T', domain: 'att.com' },
  'T-Mobile': { ticker: 'TMUS', domain: 't-mobile.com' },
  Comcast: { ticker: 'CMCSA', domain: 'comcast.com' },
  Charter: { ticker: 'CHTR', domain: 'corporate.charter.com' },
  Disney: { ticker: 'DIS', domain: 'disney.com' },
  Netflix: { ticker: 'NFLX', domain: 'netflix.com' },
  'Warner Bros. Discovery': { ticker: 'WBD', domain: 'wbd.com' },
  Paramount: { ticker: 'PARA', domain: 'paramount.com' },
  Fox: { ticker: 'FOXA', domain: 'foxcorp.com' },
  'News Corp': { ticker: 'NWSA', domain: 'newscorp.com' },
};

// ---------------------------------------------------------------------------
// Sector medians — the maturity profile of the median company in each
// industry, computed from the dataset itself. The planet profile compares a
// company against its sector's median (radar overlay + dimension ticks).
// ---------------------------------------------------------------------------

function median(values: number[]): number {
  const s = [...values].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 === 1 ? s[mid] : Math.round((s[mid - 1] + s[mid]) / 2);
}

export const SECTOR_MEDIAN: Record<Industry, MaturityTuple> = (() => {
  const groups = new Map<Industry, MaturityTuple[]>();
  for (const e of FORTUNE500_AI_COMPANIES) {
    const list = groups.get(e.industry) ?? [];
    list.push(e.m);
    groups.set(e.industry, list);
  }
  const result = {} as Record<Industry, MaturityTuple>;
  for (const [industry, lists] of groups) {
    result[industry] = [0, 1, 2, 3, 4, 5].map((i) =>
      median(lists.map((m) => m[i]))
    ) as MaturityTuple;
  }
  return result;
})();
