import { readFile } from 'fs/promises';
import path from 'path';

export type FinbenchTrack = 'asc606' | 'govcon';

export interface FinbenchSummary {
  tasks: number;
  numeric_accuracy: number | null;
  groundedness: number;
  citation_validity: number;
  structure: number;
}

export interface FinbenchTaskPublic {
  id: string;
  category: string;
  difficulty: string;
  provenance: string;
  prompt: string;
  required_citations: string[];
}

export interface FinbenchRunPublic {
  id: string;
  task_id: string;
  model_provider: string;
  model_version: string;
  numeric_accuracy: boolean | null;
  groundedness_score: number;
  citation_validity: number;
  structure_score: number;
  latency_ms: number;
  judge_rationale: string;
  response: string;
  run_at: string;
}

export type FinbenchFindingKind =
  | 'citation_gap'
  | 'numeric_miss'
  | 'groundedness_gap'
  | 'latency_outlier';

export interface FinbenchFinding {
  kind: FinbenchFindingKind;
  statement: string;
  model_version: string;
  task_ids: string[];
  detail: Record<string, number>;
}

export interface FinbenchTrendModel {
  current: number;
  prior: number | null;
  change: number | null;
}

export interface FinbenchTrend {
  prior_month: string | null;
  models: Record<string, FinbenchTrendModel>;
}

export interface FinbenchSnapshot {
  track: FinbenchTrack;
  month: string;
  scorecard: {
    track: string;
    month: string;
    models: Record<string, FinbenchSummary>;
    categories: Record<string, FinbenchSummary>;
  };
  tasks: FinbenchTaskPublic[];
  runs: FinbenchRunPublic[];
  findings: FinbenchFinding[];
  trend: FinbenchTrend;
}

export const TRACKS: { id: FinbenchTrack; label: string; accent: string }[] = [
  { id: 'asc606', label: 'ASC 606 · Revenue Recognition', accent: 'text-trajectory' },
  { id: 'govcon', label: 'Govcon · DCAA Compliance', accent: 'text-maturity-mid' },
];

/** Labels for finding kinds, keyed to deterministic derivation rules. */
export const FINDING_KIND_LABELS: Record<FinbenchFindingKind, string> = {
  citation_gap: 'Citation gap',
  numeric_miss: 'Numeric miss',
  groundedness_gap: 'Groundedness gap',
  latency_outlier: 'Latency outlier',
};

/**
 * Loads a published FinBench snapshot from public/finbench/. Snapshots are
 * generated by `finbench export-web` and contain no ground-truth answers.
 * Returns null when no snapshot has been published for the track.
 */
export async function loadSnapshot(
  track: FinbenchTrack,
): Promise<FinbenchSnapshot | null> {
  try {
    const file = path.join(process.cwd(), 'public', 'finbench', `${track}.json`);
    const raw = await readFile(file, 'utf8');
    return JSON.parse(raw) as FinbenchSnapshot;
  } catch {
    return null;
  }
}

export function modelLabel(provider: string, version: string): string {
  return `${provider} · ${version}`;
}

/** Numeric accuracy when the category has computed answers, else groundedness. */
export function cellMetric(
  runs: FinbenchRunPublic[],
): { value: number; kind: 'numeric' | 'groundedness' } {
  const numeric = runs.filter((r) => r.numeric_accuracy !== null);
  if (numeric.length > 0) {
    return {
      value: numeric.filter((r) => r.numeric_accuracy).length / numeric.length,
      kind: 'numeric',
    };
  }
  return {
    value: runs.reduce((sum, r) => sum + r.groundedness_score, 0) / runs.length,
    kind: 'groundedness',
  };
}
